In [1]:
import torch

In [2]:
x = torch.tensor([[1,2]])
x

tensor([[1, 2]])

In [3]:
y = torch.tensor([[1], [2]])
y

tensor([[1],
        [2]])

In [4]:
x.shape

torch.Size([1, 2])

In [5]:
y.shape

torch.Size([2, 1])

In [6]:
x.type

<function Tensor.type>

In [7]:
x.dtype

torch.int64

In [9]:
x = torch.tensor([[False,1,2.0]])
x

tensor([[0., 1., 2.]])

Generate a tensor object that has three rows and four columns filled with
zeros

In [11]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Generate a tensor object that has three rows and four columns filled with
ones

In [12]:
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Generate three rows and four columns of values between 0 and 10
(including the low value but not including the high value):

In [16]:
torch.randint(low=-1, high=1, size=(3,4))

tensor([[-1,  0, -1,  0],
        [-1,  0,  0, -1],
        [ 0,  0, -1,  0]])

 Generate random numbers between 0 and 1 with three rows and four
columns:

In [17]:
torch.rand(3,4)

tensor([[0.2499, 0.4976, 0.0747, 0.4648],
        [0.7849, 0.6820, 0.7441, 0.3056],
        [0.6718, 0.1329, 0.2038, 0.7133]])

Generate numbers that follow a normal distribution with three rows and
four columns:

In [18]:
torch.randn((3,4))

tensor([[-0.9927,  0.0426, -0.2535,  2.6129],
        [-0.9464,  0.7755,  0.7147,  0.3280],
        [ 0.7071,  0.2153,  0.2840, -1.4547]])

Finally, we can directly convert a NumPy array into a Torch tensor using

In [20]:
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y =  torch.tensor(x)


In [21]:
type(x)

numpy.ndarray

In [22]:
type(y)

torch.Tensor