In [1]:
import torch

* Multiplication of all the elements present in x by 10 can be performed
using the following code:

In [2]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
x*10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

* Adding 10 to the elements in x and storing the resulting tensor in y can be
performed using the following code

In [3]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

* Reshaping a tensor can be performed using the following code:

In [5]:
y = torch.tensor([2,3,1,0])
print("origin y shape", y.shape)
y = y.view(4,1)
print("reshaped y shape", y.shape)

origin y shape torch.Size([4])
reshaped y shape torch.Size([4, 1])


* Another way to reshape a tensor is by using the squeeze method, where
we provide the axis index that we want to remove. Note that this is
applicable only when the axis we want to remove has only one item in that
dimension:

In [11]:
x = torch.randn(10,1,10)
x.shape

torch.Size([10, 1, 10])

In [10]:
z1 = torch.squeeze(x, 1)
z1.shape

torch.Size([10, 10])

In [17]:
z2 = x.squeeze(1)
z2.shape

torch.Size([10, 10])

* The opposite of squeeze is unsqueeze, which means we add a dimension
to the matrix, which can be performed using the following code:

In [18]:
x =  torch.randn(10,10)
x.shape

torch.Size([10, 10])

In [19]:
z1 = x.unsqueeze(0)
z1.shape

torch.Size([1, 10, 10])

use None


In [20]:
x  = torch.randn(10,10)
z2, z3, z4 = x[None], x[:,None], x[:,:, None]
print(z2.shape)
print(z3.shape)
print(z4.shape)

torch.Size([1, 10, 10])
torch.Size([10, 1, 10])
torch.Size([10, 10, 1])


***Using None for indexing is a fancy way of unsqueezing, as shown,
and will be used often in this book for creating fake channel/batch
dimensions.***

* Matrix multiplication of two different tensors can be performed using the
following code:

In [25]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
y = torch.randint(low=1, high=100, size=(4,2))
torch.matmul(x,y)

tensor([[ 572,  365],
        [1396,  925]])

***Alternatively, matrix multiplication can also be performed by using the @
operator:***

In [26]:
x@y

tensor([[ 572,  365],
        [1396,  925]])

* Similar to concatenate in NumPy, we can perform concatenation of
tensors using the cat method

In [28]:
x =  torch.randn(10,10,10)
z = torch.cat([x,x], axis=0)
print("x shape", x.shape)
print("z shape", z.shape)

x shape torch.Size([10, 10, 10])
z shape torch.Size([20, 10, 10])


In [29]:
z = torch.cat([x,x], axis=1)
print("x shape", x.shape)
print("z shape", z.shape)

x shape torch.Size([10, 10, 10])
z shape torch.Size([10, 20, 10])


In [30]:
z = torch.cat([x,x], axis=2)
print("x shape", x.shape)
print("z shape", z.shape)

x shape torch.Size([10, 10, 10])
z shape torch.Size([10, 10, 20])


* Extraction of the maximum value in a tensor can be performed using the
following code

In [33]:
x = torch.arange(25).reshape(5,5)
print(x)
print("Max", x.shape, x.max())

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])
Max torch.Size([5, 5]) tensor(24)


* We can extract the maximum value along with the row index where the
maximum value is present

In [34]:
x.max(dim=0)

torch.return_types.max(
values=tensor([20, 21, 22, 23, 24]),
indices=tensor([4, 4, 4, 4, 4]))

***Note that, in the preceding output, we are fetching the maximum values
across dimension 0, which is the rows of the tensor. Hence, the maximum
values across all rows are the values present in the 4th `index` and hence the
indices output is all fours too***

* Furthermore, `.max` returns both the
maximum values and the location (`argmax`) of the maximum values. Similarly, the output when fetching the maximum value across columns is
as follows:

In [35]:
m, argm =  x.max(dim=1)
print(m, argm)

tensor([ 4,  9, 14, 19, 24]) tensor([4, 4, 4, 4, 4])


* The `min` operation is exactly the same as `max` but returns the minimum and
arg-minimum where applicable

* Permute the dimensions of a tensor object:

In [36]:
x =  torch.randn(10,20,30)
z = x.permute(2,0,1)
print("x shape", x.shape)
print("z shape", z.shape)

x shape torch.Size([10, 20, 30])
z shape torch.Size([30, 10, 20])


***Note that the shape of the tensor changes when we perform permute on top of the
original tensor***

***Never reshape (that is, use `tensor.view` on) a tensor to swap the
dimensions. Even though Torch will not throw an error, this is
wrong and will create unforeseen results during training. If you
need to swap dimensions, always use permute***

 Standard mathematical operations, such as `abs, add, argsort,
ceil, floor, sin, cos, tan, cumsum, cumprod, diag, eig, exp, log, log2, log10,
mean, median, mode, resize, round, sigmoid, softmax, square, sqrt, svd,
and transpose`, to name a few, can be directly called on any tensor with or without
axes where applicable