In [1]:
from torch.utils.data import Dataset, DataLoader
import torch
import torch.nn as nn

# Prepare Dataset

In [2]:
x = [[1,2],[3,4],[5,6],[7,8]]
y = [[3],[7],[11],[15]]

In [3]:
X = torch.tensor(x).float()
Y = torch.tensor(y).float()

In [4]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
X = X.to(device)
Y = Y.to(device)

In [5]:
class MyDataset(Dataset):
    def __init__(self, X, Y):
        self.X = torch.tensor(X).float()
        self.Y = torch.tensor(Y).float()
    def __len__(self):
        return len(self.X)
    def __getitem__(self, ix):
        return self.X[ix], self.Y[ix]

In [10]:
class MyNeuralNetwork(nn.Module): 
    def __init__(self):
        super().__init__()
        self.input_to_hidden = nn.Linear(2, 8)
        self.hidden_layer_activation = nn.ReLU()
        self.hidden_to_output_layer = nn.Linear(8, 1)
    def forward(self, x):
        x = self.input_to_hidden(x)
        x = self.hidden_layer_activation(x)
        x = self.hidden_to_output_layer(x)
        return x

In [6]:
ds = MyDataset(X, Y)

c:\Users\NAB\anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until
c:\Users\NAB\anaconda3\envs\pytorch\lib\site-packages\ipykernel_launcher.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  after removing the cwd from sys.path.


In [7]:
dl = DataLoader(ds, batch_size=2, shuffle=True)


In [9]:
for x, y in dl:
    print(x," \n", y)


tensor([[7., 8.],
        [5., 6.]], device='cuda:0')  
 tensor([[15.],
        [11.]], device='cuda:0')
tensor([[3., 4.],
        [1., 2.]], device='cuda:0')  
 tensor([[7.],
        [3.]], device='cuda:0')


In [12]:
my_net = MyNeuralNetwork().to(device)
loss_func = nn.MSELoss()
from torch.optim import SGD
opt = SGD(my_net.parameters(), lr=0.001)

# Training

In [13]:
import time
from tqdm import tqdm
loss_history = []
start = time.time()
for epoch in tqdm(range(50)):
    for data in dl:
        x, y = data
        opt.zero_grad()
        loss_value = loss_func(my_net(x), y)
        loss_value.backward()
        opt.step()
        loss_history.append(loss_value.item())
end = time.time()
print("Time taken: ", end-start)

100%|██████████| 50/50 [00:00<00:00, 51.87it/s]

Time taken:  0.9690015316009521


# Predicting on new data points

In [14]:
val_x = [[10, 11]]

In [15]:
val_x = torch.tensor(val_x).float().to(device)

In [16]:
my_net(val_x)

tensor([[21.1643]], device='cuda:0', grad_fn=<AddmmBackward0>)