In [4]:
import torch

In [9]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [10]:

my_tensor =  torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,
                            device=device, requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [12]:
print("device:", my_tensor.device)

device: cpu


In [13]:
print("dtype:", my_tensor.dtype)

dtype: torch.float32


In [14]:
print("shape:", my_tensor.shape)

shape: torch.Size([2, 3])


In [16]:
print("requires_grad:", my_tensor.requires_grad)

requires_grad: True


In [18]:
torch.empty(size=(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
torch.zeros(size=(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
torch.rand(size=(3,3))

tensor([[0.8908, 0.9423, 0.4120],
        [0.9981, 0.4556, 0.5999],
        [0.0174, 0.2101, 0.5478]])

In [22]:
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [28]:
torch.arange(start=0, end=5, step=1)

tensor([0, 1, 2, 3, 4])

In [24]:
torch.linspace(start=0.1, end=1, steps=10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [29]:
torch.empty(size=(1,5)).normal_(mean=0, std=1)

tensor([[ 0.7234, -0.0746, -0.9119, -0.5407, -0.0984]])

In [31]:
torch.empty(size=(1,5)).uniform_(0, 1)

tensor([[0.2418, 0.3816, 0.0969, 0.9487, 0.3389]])

In [33]:
torch.diag(torch.ones(4))

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [37]:
tensor = torch.arange(10)
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
tensor.bool()

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True])

In [39]:
tensor.short()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int16)

In [40]:
tensor.long()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
tensor.half()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

In [42]:
tensor.double()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)