In [175]:
import torch

In [176]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [177]:

my_tensor =  torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,
                            device=device, requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [178]:
print("device:", my_tensor.device)

device: cuda:0


In [179]:
print("dtype:", my_tensor.dtype)

dtype: torch.float32


In [180]:
print("shape:", my_tensor.shape)

shape: torch.Size([2, 3])


In [181]:
print("requires_grad:", my_tensor.requires_grad)

requires_grad: True


----
### Tạo tensor rỗng có các phần tử là 0 kích thước 3x3

In [182]:
torch.empty(size=(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

----
### Tạo tensor có các phần tử là 0 kích thước 3x3

In [183]:
torch.zeros(size=(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

----
### Tạo tensor có các phần tử ngẫu nhiên từ 0 đến 1 kích thước 3x3

In [184]:
torch.rand(size=(3,3))

tensor([[0.8953, 0.1064, 0.5747],
        [0.8682, 0.2824, 0.7250],
        [0.6611, 0.1205, 0.8783]])

----
### Tạo tensor là ma trận đơn vị có kích thước 3x3

In [185]:
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

----
### Tạo tensor có các phần từ giá trị bắt đầu là 0 và kết thúc 5-1 với bước nhảy là 1

In [186]:
torch.arange(start=0, end=5, step=1)

tensor([0, 1, 2, 3, 4])

----
### Tạo tensor có phần tử chạy từ 0.1 đến 1 và có 10 bước nhảy

In [187]:
torch.linspace(start=0.1, end=1, steps=10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

----
### Tạo tensor có các phần tử tuân theo phân phối chuẩn có $\sigma = 1$ và $\mu = 0$

In [188]:
torch.empty(size=(1,5)).normal_(mean=0, std=1)

tensor([[-0.0044, -0.8973, -1.8362,  0.1763, -0.0171]])

In [189]:
torch.empty(size=(1,5)).uniform_(0, 1)

tensor([[0.2896, 0.7039, 0.1781, 0.1012, 0.4166]])

----
### Tạo tensor có ma trận đường chéo có kích thước 4x4

In [190]:
torch.diag(torch.ones(4))

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

----
### Tạo tensor là một vector có giá trị chạy từ (0 đến 10-1)

In [191]:
tensor = torch.arange(10)
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Chuyển các giá trị trong tensor về kiểu dữ liệu bool

In [192]:
tensor.bool()

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True])


### Chuyển các giá trị trong tensor về kiểu dữ liệu short

In [193]:
tensor.short()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int16)


### Chuyển các giá trị trong tensor về kiểu dữ liệu long

In [194]:
tensor.long()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Chuyển các giá trị trong tensor về kiểu dữ liệu half

In [195]:
tensor.half()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)


### Chuyển các giá trị trong tensor về kiểu dữ liệu double

In [196]:
tensor.double()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

----
### Chuyển từ numpy array sang tensor và ngược lại

In [197]:
import numpy as np
np_array = np.zeros((5,5))
tensor =  torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [198]:
np_array = tensor.numpy()
np_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

----
# MATH

In [199]:
x =  torch.tensor([1, 2, 3])
y =  torch.tensor([9, 8, 7])


#### Cộng

In [200]:
z1 = torch.empty(3)
torch.add(x, y, out=z1)
z1

tensor([10., 10., 10.])

In [201]:
z2 = torch.add(x, y)
z2

tensor([10, 10, 10])

In [202]:
z2 = x + y

#### Trừ

In [203]:
z3 = torch.subtract(x, y)
z3

tensor([-8, -6, -4])

In [204]:
z3 = x - y

#### Chia

In [205]:
z4 = torch.divide(x, y)
z4

tensor([0.1111, 0.2500, 0.4286])

In [206]:
z5 = torch.true_divide(x, y)
z5

tensor([0.1111, 0.2500, 0.4286])

#### Nhân

In [207]:
z6 = torch.dot(x, y)
z6

tensor(46)

#### Nhân element-wise

In [208]:
x*y

tensor([ 9, 16, 21])

In [209]:
z7 = torch.mul(x, y)
z7

tensor([ 9, 16, 21])

### Nhân matix

In [210]:
a = torch.rand((2, 5))
b = torch.rand((5, 3))
out_bm = torch.mm(a, b)
out_bm

tensor([[0.6409, 0.4295, 0.6646],
        [1.2809, 0.7197, 1.0852]])

In [211]:
a.mm(b)

tensor([[0.6409, 0.4295, 0.6646],
        [1.2809, 0.7197, 1.0852]])

### Lũy thừa matrix

In [212]:
square_matrix = torch.rand((5, 5))
square_matrix.matrix_power(3)

tensor([[3.9019, 5.0381, 3.7060, 2.0497, 5.8802],
        [3.8000, 4.9168, 3.2198, 1.5624, 5.6494],
        [2.6435, 3.0294, 2.3689, 1.0788, 3.8500],
        [4.8914, 6.1811, 4.8810, 2.2734, 7.3320],
        [3.7634, 4.8355, 3.2252, 1.6898, 5.3936]])

### Nhân element wise

In [213]:
a = torch.rand((2, 5))
b = torch.rand((2, 5))
a * b

tensor([[7.6055e-01, 7.9042e-03, 3.3483e-01, 4.1952e-01, 1.8375e-01],
        [6.5991e-01, 2.3717e-01, 8.6755e-05, 1.6892e-01, 3.0463e-01]])

### Nhân batch

In [214]:
batch_size = 10
n = 10
m = 20
p = 30

Tạo 2 tensor có giá trị ngẫu nhiên

In [215]:
tensor_1 = torch.rand((batch_size, n, m))
tensor_2 = torch.rand((batch_size, m, p))
print("shape of tensor_1:", tensor_1.shape)
print("shape of tensor_2:", tensor_2.shape)

shape of tensor_1: torch.Size([10, 10, 20])
shape of tensor_2: torch.Size([10, 20, 30])


In [216]:
out_bmm = torch.bmm(tensor_1, tensor_2)
out_bmm.shape

torch.Size([10, 10, 30])

### Boardcasting

In [217]:
tensor_1 = torch.rand((5, 5))
tensor_2 = torch.rand((5, 5))

z = tensor_1 - tensor_2
z = tensor_1 ** tensor_2
z

tensor([[0.8185, 0.4255, 0.6569, 0.9132, 0.7942],
        [0.6774, 0.8498, 0.8990, 0.9228, 0.0074],
        [0.9941, 0.9433, 0.9919, 0.8643, 0.5919],
        [0.8020, 0.9638, 0.9825, 0.7983, 0.9753],
        [0.6289, 0.2056, 0.0653, 0.8873, 0.9860]])

### Other useful tensor operations

In [218]:
sum_x = torch.sum(x, dim=0)
sum_x

tensor(6)

In [219]:
values, indices = torch.max(x, dim=0)
values, indices

(tensor(3), tensor(2))

In [220]:
values, indices = torch.min(x, dim=0)
values, indices

(tensor(1), tensor(0))

In [221]:
abs_x = torch.abs(x)
abs_x

tensor([1, 2, 3])

In [222]:
z = torch.argmax(x, dim=0)
z

tensor(2)

In [223]:
z = torch.argmin(x, dim=0)
z

tensor(0)

In [224]:
mean_x = torch.mean(x.float(), dim=0)
mean_x

tensor(2.)

In [225]:
z = torch.eq(x, y)
z

tensor([False, False, False])

In [226]:
sorted_x, indices = torch.sort(x, dim=0, descending=False)
sorted_x, indices

(tensor([1, 2, 3]), tensor([0, 1, 2]))

In [227]:
z = torch.clamp(x, min=0)
z

tensor([1, 2, 3])

In [228]:
x = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)
x

tensor([ True, False,  True,  True,  True])

In [229]:
z = torch.any(x)
z

tensor(True)

In [230]:
z = torch.all(x)
z

tensor(False)

# Tensor Indexing

In [231]:
batch_size = 32
features = 25
x = torch.rand((batch_size, features))

In [232]:
x[0].shape

torch.Size([25])

In [233]:
x[:, 0].shape

torch.Size([32])

In [234]:
x[0,:].shape

torch.Size([25])

In [235]:
x = torch.arange(10)
indices = [2, 5, 8]
x[indices]

tensor([2, 5, 8])

In [236]:
x = torch.rand((3, 5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
x[rows, cols]


tensor([0.8233, 0.8192])

In [237]:
x = torch.arange(10)
x[(x < 2) | (x > 8)]

tensor([0, 1, 9])

In [238]:
x.remainder(2) == 0

tensor([ True, False,  True, False,  True, False,  True, False,  True, False])

In [239]:
x[x.remainder(2) == 0]

tensor([0, 2, 4, 6, 8])

In [240]:
torch.where(x > 5, x, x*2)

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [241]:
torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique()

tensor([0, 1, 2, 3, 4])

In [242]:
x.ndimension()

1

In [243]:
x.numel()

10

# Tensor Reshape

In [244]:
x = torch.arange(9)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [245]:
y = x.view(3, 3)
y

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [246]:
y = x.reshape(3, 3)
y

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [247]:
y.t()

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [253]:
y.t().contiguous().view(9)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [254]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
torch.cat((x1, x2), dim=0).shape

torch.Size([4, 5])

In [255]:
torch.cat((x1, x2), dim=1).shape

torch.Size([2, 10])

In [259]:
z = x1.view(-1)
z

tensor([0.8507, 0.3934, 0.2999, 0.1182, 0.6460, 0.4759, 0.4545, 0.3545, 0.1766,
        0.9695])

In [260]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
z.shape

torch.Size([64, 10])

In [262]:
x.shape

torch.Size([64, 2, 5])

In [263]:
z = x.permute(0, 2, 1)
z.shape

torch.Size([64, 5, 2])

In [264]:
x.unsqueeze(0).shape

torch.Size([1, 64, 2, 5])

In [265]:
x.unsqueeze(1).shape

torch.Size([64, 1, 2, 5])

In [267]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
x.shape

torch.Size([1, 1, 10])

In [268]:
x.squeeze(0).shape

torch.Size([1, 10])

In [269]:
x.squeeze(1).shape

torch.Size([1, 10])