In [1]:
import torch

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [3]:

my_tensor =  torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,
                            device=device, requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [4]:
print("device:", my_tensor.device)

device: cuda:0


In [5]:
print("dtype:", my_tensor.dtype)

dtype: torch.float32


In [6]:
print("shape:", my_tensor.shape)

shape: torch.Size([2, 3])


In [7]:
print("requires_grad:", my_tensor.requires_grad)

requires_grad: True


----
### Tạo tensor rỗng có các phần tử là 0 kích thước 3x3

In [8]:
torch.empty(size=(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

----
### Tạo tensor có các phần tử là 0 kích thước 3x3

In [9]:
torch.zeros(size=(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

----
### Tạo tensor có các phần tử ngẫu nhiên từ 0 đến 1 kích thước 3x3

In [10]:
torch.rand(size=(3,3))

tensor([[0.5630, 0.3194, 0.1476],
        [0.0491, 0.5904, 0.1993],
        [0.2375, 0.5706, 0.2797]])

----
### Tạo tensor là ma trận đơn vị có kích thước 3x3

In [11]:
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

----
### Tạo tensor có các phần từ giá trị bắt đầu là 0 và kết thúc 5-1 với bước nhảy là 1

In [12]:
torch.arange(start=0, end=5, step=1)

tensor([0, 1, 2, 3, 4])

----
### Tạo tensor có phần tử chạy từ 0.1 đến 1 và có 10 bước nhảy

In [13]:
torch.linspace(start=0.1, end=1, steps=10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

----
### Tạo tensor có các phần tử tuân theo phân phối chuẩn có $\sigma = 1$ và $\mu = 0$

In [14]:
torch.empty(size=(1,5)).normal_(mean=0, std=1)

tensor([[-1.7187, -1.0734,  0.4714, -0.8428, -1.1571]])

In [15]:
torch.empty(size=(1,5)).uniform_(0, 1)

tensor([[0.4906, 0.4843, 0.4776, 0.9258, 0.2713]])

----
### Tạo tensor có ma trận đường chéo có kích thước 4x4

In [16]:
torch.diag(torch.ones(4))

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

----
### Tạo tensor là một vector có giá trị chạy từ (0 đến 10-1)

In [17]:
tensor = torch.arange(10)
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Chuyển các giá trị trong tensor về kiểu dữ liệu bool

In [18]:
tensor.bool()

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True])


### Chuyển các giá trị trong tensor về kiểu dữ liệu short

In [19]:
tensor.short()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int16)


### Chuyển các giá trị trong tensor về kiểu dữ liệu long

In [20]:
tensor.long()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Chuyển các giá trị trong tensor về kiểu dữ liệu half

In [21]:
tensor.half()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)


### Chuyển các giá trị trong tensor về kiểu dữ liệu double

In [22]:
tensor.double()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

----
### Chuyển từ numpy array sang tensor và ngược lại

In [23]:
import numpy as np
np_array = np.zeros((5,5))
tensor =  torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [25]:
np_array = tensor.numpy()
np_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

----
# MATH

In [26]:
x =  torch.tensor([1, 2, 3])
y =  torch.tensor([9, 8, 7])


#### Cộng

In [28]:
z1 = torch.empty(3)
torch.add(x, y, out=z1)
z1

tensor([10., 10., 10.])

In [29]:
z2 = torch.add(x, y)
z2

tensor([10, 10, 10])

In [31]:
z2 = x + y

#### Trừ

In [30]:
z3 = torch.subtract(x, y)
z3

tensor([-8, -6, -4])

In [32]:
z3 = x - y

#### Chia

In [34]:
z4 = torch.divide(x, y)
z4

tensor([0.1111, 0.2500, 0.4286])

In [35]:
z5 = torch.true_divide(x, y)
z5

tensor([0.1111, 0.2500, 0.4286])

#### Nhân

In [36]:
z6 = torch.dot(x, y)
z6

tensor(46)

#### Nhân element-wise

In [38]:
x*y

tensor([ 9, 16, 21])

In [37]:
z7 = torch.mul(x, y)
z7

tensor([ 9, 16, 21])

### Nhân batch

In [39]:
batch_size = 10
n = 10
m = 20
p = 30

Tạo 2 tensor có giá trị ngẫu nhiên

In [43]:
tensor_1 = torch.rand((batch_size, n, m))
tensor_2 = torch.rand((batch_size, m, p))
print("shape of tensor_1:", tensor_1.shape)
print("shape of tensor_2:", tensor_2.shape)

shape of tensor_1: torch.Size([10, 10, 20])
shape of tensor_2: torch.Size([10, 20, 30])


In [42]:
out_bmm = torch.bmm(tensor_1, tensor_2)
out_bmm.shape

torch.Size([10, 10, 30])